INSERT INTO person (name, publicPlace, number, complement, neighborhood, cep, city, state, enabled) VALUES 
('Patten Readshall', 'Commercial', '1', 'Hill', 'Budapest', '12.138-90', 'Milano', 'HU', true),
('Anastasie Atheis', 'Mandrake', '9998', 'Crossing', 'Runsonglaozhai', '65.755-89', 'Salt Lake City', 'CN', false),
('Eziechiele Romney', 'Surrey', '2', 'Plaza', 'Conceição do Jacuípe', '44.245-00', 'Knoxville', 'BR', false),
('Sheela Tongs', 'International', '77', 'Circle', 'Karangjaladri', null, 'Yoro', 'ID', false),
('Sisile Ollin', 'Springs', '211', 'Point', 'Lage', '49.600-16', 'Fengping', 'PT', true),
('Ram Vasyuchov', 'Bultman', '7637', 'Park', 'Killarney', '77.658-56', 'Phùng', 'CA', false),
('Zsa zsa Buston', 'Chive', '6626', 'Parkway', 'Wuquan', '74.658-56', 'Dziadkowice', 'CN', true),
('Boote Killby', 'Fisk', '22', 'Way', 'Mâcon', '71.024-89', 'Ipala', 'FR', true),
('Flori Parysowna', 'Kropf', '73', 'Road', 'Cipicung', '97.658-56', 'Borūjerd', 'ID', false),
('Ellynn Gethouse', 'Oak Valley', '70', 'Parkway', 'Frederico Westphalen', '98.400-00', 'Verin Artashat', 'BR', true),
('Layney Sherman', 'Armistice', '3', 'Parkway', 'Fálanna', '37.658-56', 'Hoàn Kiếm', 'GR', false),
('Devina Orht', 'Ramsey', '150', 'Hill', 'Hasuda', '34.901-91', 'Cácota', 'JP', true),
('Lettie Ferrieri', 'Evergreen', '548', 'Plaza', 'Kandhkot', '79.160-78', 'Tabalong', 'PK', true),
('Marc Baynon', 'Fremont', '8106', 'Drive', 'Katori-shi', '31.124-26', 'Yitang', 'JP', true),
('Juliet Smiley', 'Bartillon', '2123', 'Parkway', 'Dzhubga', '35.928-44', 'Nikolina Gora', 'RU', false),
('Gale Polleye', 'Dexter', '2', 'Center', 'Jiangyou', '45.758-00', 'Mondlo', 'CN', true),
('Vivie Rase', 'Sundown', '17', 'Street', 'Weyburn', '45.758-88', 'Portoviejo', 'CA', false),
('Corine Bracer', 'Bunker Hill', '0', 'Street', 'Pasirlimus', '65.768-88', 'Caraguatatuba', 'ID', true),
('Dari Gallard', 'Riverside', '1730', 'Terrace', 'Gontar', '55.728-68', 'Az̧ Z̧a‘āyin', 'ID', true),
('Silvanus Readshall', 'Rigney', '784', 'Street', 'Örebro', '70134-43', 'Sortavala', 'SE', true);
